version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'MDS'
      MYSQL_USER: 'Jumia'
      MYSQL_PASSWORD: 'Jumia@2022'
      MYSQL_ROOT_PASSWORD: 'Jumia@2022'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  rabbit-mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-mq
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    restart: always
    networks:
      - dev-network
volumes:
  my-db:
networks:
  dev-network:
    driver: bridge